apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: kubelet-kill-chaos-sur-9
  namespace: litmus
  labels:
    subject: kubelet-kill-chaos_litmus
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
      - name: targetNode
        value: ${TargetNode}
      - name: chaosDuration
        value: ${ChaosDuration}
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: custom-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: kubelet-service-kill-wqr
            template: kubelet-service-kill-wqr
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: kubelet-service-kill-wqr
            path: /tmp/kubelet-service-kill-wqr.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Kills the kubelet service on the application node to check the resiliency.
                kind: ChaosExperiment

                metadata:
                  name: kubelet-service-kill
                  labels:
                    name: kubelet-service-kill
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                    image: litmuschaos/go-runner:2.14.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name kubelet-service-kill
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: NODE_LABEL
                        value: ""
                      - name: LIB_IMAGE
                        value: ubuntu:16.04
                      - name: TARGET_NODE
                        value: ""
                    labels:
                      name: kubelet-service-kill
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/service-kill: "true"
                      app.kubernetes.io/version: 2.14.0
      container:
        args:
          - kubectl apply -f /tmp/kubelet-service-kill-wqr.yaml -n
            {{workflow.parameters.adminModeNamespace}} &&  sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:2.14.0
    - name: kubelet-service-kill-wqr
      inputs:
        artifacts:
          - name: kubelet-service-kill-wqr
            path: /tmp/chaosengine-kubelet-service-kill-wqr.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: kubelet-service-kill-wqr
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                spec:
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: kubelet-service-kill
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "{{workflow.parameters.chaosDuration}}"
                            - name: TARGET_NODE
                              value: "{{workflow.parameters.targetNode}}"
                        probe: []
      container:
        args:
          - -file=/tmp/chaosengine-kubelet-service-kill-wqr.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:2.14.0
