apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: custom-1669873038
  namespace: litmus
  labels:
    subject: custom_litmus
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: custom-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: node-memory-hog-6jx
            template: node-memory-hog-6jx
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: node-cpu-hog-16m
            path: /tmp/node-cpu-hog-16m.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Give a cpu spike on a node belonging to a deployment
                kind: ChaosExperiment
                metadata:
                  name: node-cpu-hog
                  labels:
                    name: node-cpu-hog
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                    image: litmuschaos/go-runner:2.14.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name node-cpu-hog
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: NODE_CPU_CORE
                        value: ""
                      - name: CPU_LOAD
                        value: "100"
                      - name: TARGET_NODES
                        value: ""
                      - name: NODE_LABEL
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:2.14.0
                      - name: NODES_AFFECTED_PERC
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: node-cpu-hog
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.14.0
          - name: kubelet-service-kill-sgo
            path: /tmp/kubelet-service-kill-sgo.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Kills the kubelet service on the application node to check the resiliency.
                kind: ChaosExperiment

                metadata:
                  name: kubelet-service-kill
                  labels:
                    name: kubelet-service-kill
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                    image: litmuschaos/go-runner:2.14.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name kubelet-service-kill
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: NODE_LABEL
                        value: ""
                      - name: LIB_IMAGE
                        value: ubuntu:16.04
                      - name: TARGET_NODE
                        value: ""
                    labels:
                      name: kubelet-service-kill
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/service-kill: "true"
                      app.kubernetes.io/version: 2.14.0
          - name: node-memory-hog-6jx
            path: /tmp/node-memory-hog-6jx.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Give a memory hog on a node belonging to a deployment
                kind: ChaosExperiment
                metadata:
                  name: node-memory-hog
                  labels:
                    name: node-memory-hog
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                    image: litmuschaos/go-runner:2.14.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name node-memory-hog
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "120"
                      - name: MEMORY_CONSUMPTION_PERCENTAGE
                        value: ""
                      - name: MEMORY_CONSUMPTION_MEBIBYTES
                        value: ""
                      - name: NUMBER_OF_WORKERS
                        value: "1"
                      - name: TARGET_NODES
                        value: ""
                      - name: NODE_LABEL
                        value: ""
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:2.14.0
                      - name: NODES_AFFECTED_PERC
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: node-memory-hog
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.14.0
      container:
        args:
          - kubectl apply -f /tmp/node-memory-hog-6jx.yaml -n
            {{workflow.parameters.adminModeNamespace}} &&  sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:2.14.0
    - name: node-memory-hog-6jx
      inputs:
        artifacts:
          - name: node-memory-hog-6jx
            path: /tmp/chaosengine-node-memory-hog-6jx.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: node-memory-hog-6jx
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                spec:
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: node-memory-hog
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "120"
                            - name: NODES_AFFECTED_PERC
                              value: ""
                            - name: TARGET_NODES
                              value: gke-litmus-chaos-gke-litmus-nodepool--577b7a16-g7m5
                            - name: MEMORY_CONSUMPTION_PERCENTAGE
                              value: "0"
                            - name: MEMORY_CONSUMPTION_MEBIBYTES
                              value: "0"
                        probe: []
      container:
        args:
          - -file=/tmp/chaosengine-node-memory-hog-6jx.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:2.14.0